### ISSUE TITLE
Improve text selection

### ISSUE THREAD

**Issue by samuelhalff** [jichang/unionpdf#1]
Hi there,
Thanks for the work.
Tried the demo but text selection is very much off.
Would be interested in using a react Pdfium implementation for rendering and selecting text, but there seems to be a lot of work on text selection..
Let me know if you believe text selection can be improved without too much work and I would be curious to look into it.
Thanks,
Sam

**Comment by jichang** [comment]
@samuelhalff it's a known issue and I haven't find time to look into it yet.

1. this function failed to read some text rects becacuse sometime charIndex is -1
https://github.com/jichang/unionpdf/blob/f4605e694fa047e63678a289adf2d2e3034a37a4/packages/engines/src/pdfium/engine.ts#L1382 
2. all the text rects are located with absolution positioning, it will affect the selection handling

Not sure how much work it needs to fix those issues though
