### ISSUE TITLE
Update PDFium to a More Recent Version

### ISSUE THREAD

**Issue by nguyenyou** [jichang/unionpdf#11]
Hi, thank you for your work on the library! It's been a huge help in my projects. I was wondering if you might consider updating the PDFium version when you have the chance. A more recent version would be fantastic for some of the new features/bug fixes/ performance improvements in PDFium. No rush, of course—whenever it's convenient for you. Thanks again for maintaining this library!

**Comment by jichang** [comment]
main branch has been updated to [chromium/6815](https://pdfium.googlesource.com/pdfium/+/refs/heads/chromium/6815)

**Comment by nguyenyou** [comment]
Thank you very much @jichang ! 😁
