### ISSUE TITLE
Feature request: Github Action workflow for building wasm

### ISSUE THREAD

**Issue by nguyenyou** [jichang/unionpdf#5]
Similar to this: https://github.com/paulocoutinhox/pdfium-lib, can you provide a workflow for building pdfium wasm using by this library. Currently, looks like we have to build the wasm locally and push to Github.

Thank you for your awesome work.

**Comment by jichang** [comment]
@nguyenyou May I know what's your use case? Do you want to use the wasm file directly ?

**Comment by nguyenyou** [comment]
Hi @jichang,

I’d prefer a reproducible way to build the WASM file instead of using it directly, as this would allow transparency and security. I’m also looking to upgrade to the latest PDFium version. I couldn’t get the Docker build to work on my Mac, so having a GitHub Actions workflow or similar would be very helpful for building it myself.

Thanks!

**Comment by nguyenyou** [comment]
Hi @jichang 

I noticed that the GitHub Action workflow may occasionally get stuck at the keyboard-configuration step during the configuration process. To resolve this issue, the following modification could help:

```
RUN apt-get update && \
    apt-get install -y keyboard-configuration && \
    echo 'keyboard-configuration keyboard-configuration/layout select "English (US)"' | debconf-set-selections && \
    echo 'keyboard-configuration keyboard-configuration/variant select "English (US)"' | debconf-set-selections && \
    dpkg-reconfigure -f noninteractive keyboard-configuration
```

Adding this block before the line `RUN bash -x ./pdfium/build/install-build-deps.sh`:

```
RUN apt-get update && \
    apt-get install -y keyboard-configuration && \
    echo 'keyboard-configuration keyboard-configuration/layout select "English (US)"' | debconf-set-selections && \
    echo 'keyboard-configuration keyboard-configuration/variant select "English (US)"' | debconf-set-selections && \
    dpkg-reconfigure -f noninteractive keyboard-configuration
RUN bash -x ./pdfium/build/install-build-deps.sh
```

I've tried several ways and look like this one happen to work.

**Comment by jichang** [comment]
@nguyenyou seems you already have your own workflow to build the wasm, I suggest you maintain it separately, I only have a Windows WSL system for this project, it really add extra work for develping/testing this kind of features.

**Comment by nguyenyou** [comment]
Hi @jichang,

I agree that this is a lower priority feature compared to others. However, I submitted this feature request because I haven't yet been able to successfully complete the workflow. While I understand it's not an urgent need, I believe it would be a valuable addition. The binary WASM file currently operates like a “black box,” and having a transparent, reproducible process for building and publishing it would significantly enhance the integrity and trustworthiness of the library.

**Comment by jichang** [comment]
@nguyenyou can you post the error you met when you build WASM on MacOS? I prefer everyone build their own wasm or engine wrapper, there's too much parameters when running emscripten, everyone will have their own needs sooner or later, I don't want to introduce that problem into this repo though.

**Comment by jichang** [comment]
https://github.com/jichang/unionpdf/actions/workflows/artifact.yml

For everyone who want to build or download the wasm file, you can check this action. But I do suggest you build your own wasm file by forking the repo or packages/pdfium.

**Comment by nguyenyou** [comment]
Thanks a lot @jichang
