### ISSUE TITLE
Feature request: Get Doc Permissions

### ISSUE THREAD

**Issue by nguyenyou** [jichang/unionpdf#6]
It seems that the engine currently does not support the [FPDF_GetDocPermissions](https://pdfium.patagames.com/help/html/M_Patagames_Pdf_Pdfium_FPDF_GetDocPermissions.htm) method. There are cases where we need to determine whether the PDF file allows Print/Copy functions. This feature is similar to the [PDF.js getPermissions API](https://github.com/mozilla/pdf.js/pull/10033).

**Comment by jichang** [comment]
implemented in v0.30.0

**Comment by nguyenyou** [comment]
Thank you very much 🎉
