### ISSUE TITLE
Feature request: better search feature

### ISSUE THREAD

**Issue by nguyenyou** [jichang/unionpdf#9]
It would be better if the library supports better search feature, like collecting all match results and allow jumping to and highlighting each match.

**Comment by jichang** [comment]
For anyone who want this, the latest version 0.31.0 has the basic support for this, you need to add the ```PdfPageDecorationsLayer```

```
                    <PdfPages
                      prerenderRange={[-1, 1]}
                      cacheRange={[-1, 1]}
                      pageLayers={[
                        PdfPageCanvasLayer,
                        PdfPageTextLayer,
                        PdfPageAnnotationsLayer,
                        PdfPageEditorLayer,
                        PdfPageDecorationsLayer,
                      ]}
                    />
```

Right now, it's just basic support that assume the keyword is always in one line and also the position is not always accurate, one or 2 character might not be highlighted, but I don't have much time for improve it now.
